# Create Sample text file to load
with open("sample.txt", "w") as f:
    f.write("This is a sample text file.\n")
    f.write("It contains multiple lines of text.\n")
    f.write("This is the third line.\n")
    f.write("This is the fourth line.\n")
    f.write("This is the fifth line.\n")
    f.write("This is the sixth line.\n")
    f.write("This is the seventh line.\n")
    f.write("This is the eighth line.\n")
    f.write("This is the ninth line.\n")
    f.write("This is the tenth line.\n")
    f.write("This is the eleventh line.\n")
    f.write("This is the twelfth line.\n")
    f.write("This is the thirteenth line.\n")
    f.write("This is the fourteenth line.\n")
    f.write("This is the fifteenth line.\n")
    f.write("This is the sixteenth line.\n")
    f.write("This is the seventeenth line.\n")
    f.write("This is the eighteenth line.\n")
    f.write("This is the nineteenth line.\n")
    f.write("This is the twentieth line.\n")

print("Sample text file 'sample.txt' created successfully.")